import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import 'package:frusan_precios/src/services/usuario_service.dart';
import 'package:frusan_precios/src/services/auth_service.dart';
//import 'package:frusan_precios/src/models/user_model.dart';

///Used to create user - dependant object that need to be accesible by all widgets
///this widget should live above [MaterialApp]
///See [AuthWidget], a descendant widget that consumes the snapshot generated by this builder
class AuthWidgetBuilder extends StatelessWidget {
  const AuthWidgetBuilder({Key key, @required this.builder}) : super(key: key);
  final Widget Function(BuildContext, AsyncSnapshot<UserInside>) builder;

  @override
  Widget build(BuildContext context) {
    final _authService = Provider.of<AuthService>(context, listen: true);

    return StreamBuilder<UserInside>(
        stream: _authService.onAuthStateChanged,
        builder: (context, snapshot) {
          final user = snapshot.data;
          if (user != null) {
            return MultiProvider(
              providers: [
                Provider<UserInside>.value(value: user),
                Provider(create: (context) => UsuarioService()),
                //Provider(create: (context) => SeguridadInfoService()),
                //Provider(create: (context) => MenuView()),
                //Provider<DatabaseService>(create: (_) => DatabaseService(uid: user.uid))
              ],
              child: builder(context, snapshot),
            );
          }

          return builder(context, snapshot);
        });
  }
}
